### ISSUE TITLE
ChromeDriver version 119: Started getting all the console logs in the results window when running Selenium automation scripts in headless mode

### ISSUE THREAD

**Issue by bhawna0612** [sitespeedio/chromedriver#16]
I am working on Selenium Python scripts and when running the script, I started getting the DevTools listening  message after updating the chrome browser to 119.0.6045.124

"DevTools listening on ws://127.0.0.1:53880/devtools/browser/ba02b787-bde2-46a5-8972-3a88b8ddfb06"

Please see the full details in this issue https://github.com/SeleniumHQ/selenium/issues/13095

This is very annoying. Please provide a solution ASAP

**Comment by soulgalore** [comment]
Hi @bhawna0612 this tool just download the Chromedriver. Please add the bug at https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by paularnaud2** [comment]
I have created a Chromium issue here:
https://issues.chromium.org/issues/434633822
